Repository openstack-k8s-operators/octavia-operator, pull requests merged in 2023-11, with the labels that each got.

#193 Disable HTTP2 in webhooks
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  main.go
Labels: lgtm, approved

#194 required infra annotations for OCP 4.14+
  config/manifests/bases/octavia-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#169 switch to structured logging
  controllers/amphoracontroller_controller.go
  controllers/octavia_controller.go
  controllers/octaviaapi_controller.go
  main.go
Labels: ok-to-test, lgtm, approved

#196 Disable HTTP2 in webhooks
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  main.go
Labels: lgtm, approved

#195 Send container logs to stdout
  templates/octavia/config/db-sync-config.json
  templates/octavia/config/octavia.conf
  templates/octaviaamphoracontroller/config/octavia-healthmanager-config.json
  templates/octaviaamphoracontroller/config/octavia-housekeeping-config.json
  templates/octaviaamphoracontroller/config/octavia-worker-config.json
  templates/octaviaamphoracontroller/config/octavia.conf
  templates/octaviaapi/config/octavia-api-config.json
  templates/octaviaapi/config/octavia-driver-agent-config.json
  templates/octaviaapi/config/octavia.conf
Labels: lgtm, approved

#187 allow customize metrics and health port when run local
  Makefile
Labels: lgtm, approved

#190 Loadbalancer management network
  api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
  api/bases/octavia.openstack.org_octavias.yaml
  api/v1beta1/amphoracontroller_types.go
  api/v1beta1/conditions.go
  api/v1beta1/octavia_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
  config/crd/bases/octavia.openstack.org_octavias.yaml
  controllers/amphoracontroller_controller.go
  controllers/octavia_controller.go
  go.mod
  go.sum
  main.go
  pkg/amphoracontrollers/const.go
  pkg/amphoracontrollers/lb_mgmt_network.go
  pkg/octavia/client.go
  templates/octaviaamphoracontroller/config/octavia.conf
Labels: lgtm, approved

#200 Create Nova flavors for Octavia
  controllers/amphoracontroller_controller.go
  pkg/amphoracontrollers/flavors.go
  pkg/amphoracontrollers/lb_mgmt_network.go
  pkg/octavia/client.go
  templates/octaviaamphoracontroller/config/octavia.conf
Labels: lgtm, approved

#202 Use the Internal endpoint for the OpenStack clients
  pkg/octavia/client.go
Labels: lgtm, approved

#201 Various fixes for install_yamls_setup
  install_yamls_setup/roles/podified_cp/files/clouds.yaml
  install_yamls_setup/roles/podified_cp/files/launch.json
  install_yamls_setup/roles/podified_cp/files/octavia_v1beta1_octavia.yaml
  install_yamls_setup/roles/podified_cp/tasks/main.yaml
Labels: approved

#204 Cert management
  api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
  api/bases/octavia.openstack.org_octavias.yaml
  api/v1beta1/amphoracontroller_types.go
  config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
  config/crd/bases/octavia.openstack.org_octavias.yaml
  config/samples/octavia_v1beta1_octavia.yaml
  controllers/amphoracontroller_controller.go
  pkg/amphoracontrollers/amphora_certs.go
  pkg/amphoracontrollers/deployment.go
  pkg/amphoracontrollers/volumes.go
  templates/octaviaamphoracontroller/config/octavia.conf
Labels: lgtm, approved

#205 Revert "Cert management"
  api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
  api/bases/octavia.openstack.org_octavias.yaml
  api/v1beta1/amphoracontroller_types.go
  config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
  config/crd/bases/octavia.openstack.org_octavias.yaml
  config/samples/octavia_v1beta1_octavia.yaml
  controllers/amphoracontroller_controller.go
  pkg/amphoracontrollers/amphora_certs.go
  pkg/amphoracontrollers/deployment.go
  pkg/amphoracontrollers/volumes.go
  templates/octaviaamphoracontroller/config/octavia.conf
Labels: lgtm, approved
