Repository openstack-k8s-operators/octavia-operator, pull requests merged in 2024-06, with the labels that each got.

#315 Fix missing config for policy file override
  templates/octaviaapi/config/octavia-api-config.json
Labels: lgtm, approved

#316 Update install_yamls setup role
  install_yamls_setup/ansible.cfg
  install_yamls_setup/roles/podified_cp/tasks/main.yaml
Labels: approved

#318 Use NAD parameters to configure the Octavia resources
  api/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
  api/bases/octavia.openstack.org_octavias.yaml
  api/v1beta1/amphoracontroller_types.go
  api/v1beta1/octavia_types.go
  config/crd/bases/octavia.openstack.org_octaviaamphoracontrollers.yaml
  config/crd/bases/octavia.openstack.org_octavias.yaml
  controllers/octavia_controller.go
  pkg/amphoracontrollers/daemonset.go
  pkg/octavia/lb_mgmt_network.go
  pkg/octavia/network_consts.go
  pkg/octavia/network_parameters.go
  templates/octaviaamphoracontroller/bin/octavia_controller_start.sh
  templates/octaviaamphoracontroller/bin/octavia_mgmt_subnet_route.py
  templates/octaviaamphoracontroller/bin/octavia_status.py
  templates/octaviaamphoracontroller/config/octavia-healthmanager-config.json
  templates/octaviaamphoracontroller/config/octavia-housekeeping-config.json
  templates/octaviaamphoracontroller/config/octavia-worker-config.json
Labels: lgtm, approved

#321 update csv as generated
  config/manifests/bases/octavia-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#311 Fix previously unset "Ready" conditions
  controllers/octavia_controller.go
Labels: lgtm, approved

#317 🐛 OSPRH-7546 - return a fatal error if server CA pass secret isn't found
  controllers/octavia_controller.go
  pkg/octavia/amphora_certs.go
Labels: ok-to-test, lgtm, approved

#303 Predictable ips
  controllers/amphoracontroller_controller.go
  controllers/octavia_controller.go
  pkg/amphoracontrollers/daemonset.go
  pkg/amphoracontrollers/volumes.go
  pkg/octavia/const.go
  pkg/octavia/lb_mgmt_network.go
  pkg/octavia/network_consts.go
  templates/octaviaamphoracontroller/bin/ip_advertisement.py
  templates/octaviaamphoracontroller/bin/octavia_controller_start.sh
  templates/octaviaamphoracontroller/bin/octavia_hm_advertisement.py
  templates/octaviaamphoracontroller/bin/setipalias.py
  templates/octaviaamphoracontroller/config/octavia.conf
Labels: lgtm, approved

#322 Fixed setipalias with IPv6 addresses
  templates/octaviaamphoracontroller/bin/setipalias.py
Labels: lgtm, approved

#324 Add missing configuration directory
  templates/octaviaamphoracontroller/bin/octavia_controller_start.sh
Labels: lgtm, approved

#326 Add missing RBAC to get the list of nodes
  config/rbac/role.yaml
  controllers/amphoracontroller_controller.go
  controllers/octavia_controller.go
Labels: lgtm, approved

#327 Fix amphora image conditions
  api/v1beta1/conditions.go
  controllers/octavia_controller.go
Labels: lgtm, approved

#329 Fixed number of workers for amphora controller
  templates/octaviaamphoracontroller/config/octavia.conf
Labels: lgtm, approved

#331 Revert "Wait for DB writes to propagate (causality checks)"
  templates/octavia/config/octavia.conf
  templates/octaviaamphoracontroller/config/octavia.conf
  templates/octaviaapi/config/octavia.conf
Labels: lgtm, approved

#330 update finalzier to CRD doc
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  tests/kuttl/tests/octavia_scale/02-assert.yaml
  tests/kuttl/tests/octavia_scale/03-assert.yaml
  tests/kuttl/tests/octavia_scale/04-assert.yaml
  tests/kuttl/tests/octavia_scale/05-errors.yaml
Labels: lgtm, approved

#335 Ensure bundles include all the Required Infrastructure Annotations
  config/manifests/bases/octavia-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#334 Fix missing owns in octavia controller
  controllers/octavia_controller.go
Labels: lgtm, approved
